FROM mysql

ENV MYSQL_DATABASE=video \
    MYSQL_ROOT_PASSWORD=awodiuajowidjawjiodaoijo \
    MYSQL_USER=Bobbeh \
    MYSQL_PASSWORD=Password

COPY ./video_schema.sql /docker-entrypoint-initdb.d/schema.sql